"""create flights telemetry_points events

Revision ID: 331752b5ed92
Revises:
Create Date: 2026-07-24 17:22:51.889814

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "331752b5ed92"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flights",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("aircraft_type", sa.String(length=64), nullable=False),
        sa.Column("tail_number", sa.String(length=32), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("origin_label", sa.String(length=16), nullable=True),
        sa.Column("destination_label", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flight_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["flight_id"], ["flights.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_flight_id"), "events", ["flight_id"], unique=False)
    op.create_table(
        "telemetry_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flight_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("altitude_ft", sa.Float(), nullable=False),
        sa.Column("heading_true_deg", sa.Float(), nullable=False),
        sa.Column("pitch_deg", sa.Float(), nullable=False),
        sa.Column("bank_deg", sa.Float(), nullable=False),
        sa.Column("indicated_airspeed_kt", sa.Float(), nullable=False),
        sa.Column("vertical_speed_fpm", sa.Float(), nullable=False),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("on_ground", sa.Boolean(), nullable=False),
        sa.Column("throttle_pct", sa.Float(), nullable=False),
        sa.Column("flaps_deg", sa.Float(), nullable=False),
        sa.Column("gear_down", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["flight_id"], ["flights.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flight_id", "sequence", name="uq_telemetry_flight_sequence"),
    )
    op.create_index(
        "ix_telemetry_flight_elapsed", "telemetry_points", ["flight_id", "elapsed_ms"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_telemetry_flight_elapsed", table_name="telemetry_points")
    op.drop_table("telemetry_points")
    op.drop_index(op.f("ix_events_flight_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("flights")
    # ### end Alembic commands ###
